services:
#  redis:
#    image: redis:8-alpine
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - llm_log_processor_redis_volume:/data
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      timeout: 2s
#      retries: 5
#      interval: 10s

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - llm_log_processor_postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: secret

  llm-log-processor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - postgres
    env_file:
      - .env

volumes:
  llm_log_processor_redis_volume:
  llm_log_processor_postgres_volume: