services:
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - llm_log_pipeline_rabbitmq_volume:/var/lib/rabbitmq

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - llm_log_pipeline_postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: secret

  llm-log-pipeline:
#    image: sogbey/llm_log_pipeline:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - .env

volumes:
  llm_log_pipeline_redis_volume:
  llm_log_pipeline_postgres_volume:
  llm_log_pipeline_rabbitmq_volume: