name: Continuous Integration Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests-lints-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Go mod tidy check
        run: |
          go mod tidy
          git diff --exit-code

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./...