name: Build and Push To DockerHub

on:
  workflow_run:
    workflows: ["Continuous Integration Run"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Go Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password:  ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push with Buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/llm_log_pipeline:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/llm_log_pipeline:${{ github.event.workflow_run.head_sha }}
          platforms: linux/amd64, linux/arm64
